services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
      image: mongo:6.0
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db

  user-service:
    build: ./services/user-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=users_db
    depends_on:
      - postgres
    volumes:
      - ./services/user-service:/app

  product-service:
    build: ./services/product-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://mongo:27017/products_db
    depends_on:
      - mongo
    volumes:
      - ./services/product-service:/app


  order-service:
    build: ./services/order-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=orders_db
    depends_on:
      - postgres
    volumes:
      - ./services/order-service:/app


  notification-service:
    build: ./services/notification-service
    ports:
      - "5004:5004"
    environment:
      - PORT=5004

  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - product-service
      - order-service
      - notification-service
    environment:
      - PORT=4000

volumes:
  postgres-data:
  mongo-data:
