name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-frontend:
    name: Build Next.js App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

  install-microservices:
    name: Install Backend Microservices
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, product-service, order-service, notification-service]
    defaults:
      run:
        working-directory: services/${{ matrix.service }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Confirm service setup
        run: echo "${{ matrix.service }} setup complete"

      - name: Run service tests
        if: matrix.service == 'user-service' || matrix.service == 'product-service'
        run: npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t likrotdb2025/${{ matrix.service }}:latest .

      - name: Push Docker image to Docker Hub
        run: docker push likrotdb2025/${{ matrix.service }}:latest
